[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 5, y = 2 }
decorations = "full"
dynamic_title = true
opacity = 0.9
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14

[scrolling]
history = 10000
multiplier = 3

[terminal]
shell = "/bin/zsh"

[mouse]
hide_when_typing = true
